// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbpkhtjowohkremqncmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1icGtodGpvd29oa3JlbXFuY21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDY3OTksImV4cCI6MjA2MTUyMjc5OX0.uuHyGff04S9415KMSggLm0oH1v_3iEVeP88EnaQB8Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);